kind: pipeline
name: Build Bot

steps:
- name: Pixel Experience - Gemini
  image: baalajimaestro/android_build:latest
  environment:
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - echo gemini > /tmp/device
  - echo xiaomi > /tmp/oem
  - bash ./setup.sh